[proxmox_servers]
# IMPORTANT: Replace fake-ip-address with the actual IP address of your node
asus ansible_host=fake-ip-address ansible_user=root ansible_ssh_pass=YOUR_PASSWORD_HERE

[proxmox_servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[webservers]
# VMs will be added here

[databases]
# Database VMs will be added here
