[proxmox_servers]
# Host nodes for proxmox commands if needed
asus ansible_host=192.168.1.101 ansible_user=root

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[base]
# All nodes go here to get Docker and basic utilities
infra-node ansible_host=192.168.1.59 ansible_user=ubuntu ansible_ssh_user=ubuntu
monitor-node ansible_host=192.168.1.61 ansible_user=root ansible_ssh_user=root
app-node ansible_host=192.168.1.62 ansible_user=ubuntu ansible_ssh_user=ubuntu

[base:vars]
ansible_become=yes
ansible_become_method=sudo


[infra]
# Core routing and DNS services
infra-node

[monitoring]
# Observability stack nodes
monitor-node

[ai]
# AI self-hosted stack (Firecrawl, SearXNG, Qdrant, Langfuse, Dify, n8n)
app-node

[apps]
# General application services (Forgejo, Docmost, n8n) -- deploy on separate node if needed
# app-node
