[proxmox_servers]
# Replace with your actual Proxmox server details
proxmox1 ansible_host=proxmox.selfhost.io.vn ansible_user=root

[proxmox_servers:vars]
# Common variables for all proxmox servers
ansible_ssh_common_args='-o StrictHostKeyChecking=no'